# Generated by Django 3.2.4 on 2021-06-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefour',
            name='t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamefour',
            name='t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamefour',
            name='t3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamefour',
            name='t4',
            field=models.IntegerField(default=0),
        ),
    ]
