# Generated by Django 3.2.4 on 2021-06-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummy', '0002_auto_20210628_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamefour',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(to='rummy.GameFour'),
        ),
    ]
